Solution/Company.Project.Web.Admin/Areas/Admin/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using Company.Project.Application.Service.Interface;
using Company.Project.Infrastructure.Common;
using Z.Nlayer.Domain.Base;
using Company.Project.Domain.Model;
using Company.Project.Domain.Model.DTO;
using Company.Project.Domain.Model.DTO.Manager;
using Company.Project.Infrastructure.Common.Enums;
using Company.Project.Web.Admin.Areas.Admin.Lib;
using Newtonsoft.Json;
using Z.Nlayer.Utility;
using Z.Nlayer.Utility.Extensions;
using Company.Project.Web.Areas.Admin.Attrbute;
using Company.Project.Web.Admin.Lib;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Npoi.Core.SS.Formula.Functions;

namespace Company.Project.Web.Areas.Admin.Controllers
{
    [FormHandle]
    public class SystemController : BaseController
    {
        private readonly IProject_Manager_BaseInfoServices _baseInfoServices;
        private readonly IProject_SYS_ModuleServices _moduleServices;
        private readonly IProject_SYS_ModuleActionServices _moduleActionServices;
        private readonly IProject_SYS_RoleServices _roleServices;
        private readonly IProject_SYS_WeChatSettingServices _weChatSettingServices;
        private readonly IProject_Manager_LogServices _logServices;
        private readonly IProject_SYS_ProvinceServices _provinceServices;
        private readonly IProject_SYS_CityServices _cityServices;
        private readonly IProject_SYS_DistrictServices _districtServices;
        private readonly ILocalCommon _localCommon;
        public SystemController(
            IProject_Manager_BaseInfoServices baseInfoServices,
            IProject_SYS_ModuleServices moduleServices,
            IProject_SYS_ModuleActionServices moduleActionServices,
            IProject_SYS_RoleServices roleServices,
            IProject_Manager_LogServices logServices,
            IProject_SYS_WeChatSettingServices weChatSettingServices,
            IProject_SYS_ProvinceServices provinceServices,
            IProject_SYS_CityServices cityServices,
            IProject_SYS_DistrictServices districtServices, ILocalCommon localCommon
            ):base(localCommon)
        {
            _baseInfoServices = baseInfoServices;
            _moduleServices = moduleServices;
            _moduleActionServices = moduleActionServices;
            _roleServices = roleServices;
            _logServices = logServices;
            _weChatSettingServices = weChatSettingServices;
            _provinceServices = provinceServices;
            _cityServices = cityServices;
            _districtServices = districtServices;
            _localCommon = localCommon;
        }
        #region 公共部分
        public async Task<IActionResult> GetFatherModule(Guid fatherId, Guid itemId)
        {
            return Json(await _moduleServices.GetFatherModule(fatherId, itemId));
        }
        public IActionResult GetEnumManagerState(Enum_ManagerUserState? code = null, bool isEmpty = false)
        {
            return Json(EnumHelper.EnumTypeGetListItem<Enum_ManagerUserState>(code?.GetValueToInt().ToString(), isEmpty));
        }
        public async Task<IActionResult> GetRoeLsit()
        {
            return Json(SelectListItemHelper.GetListByT((await _roleServices.GetManyAsync(new DirectSpecification<Project_SYS_Role>(x => !x.IsDeleted))).Select(x => new SelectListItem()
            {
                Text = x.RoleName,
                Value = x.ID.ToString()

            }), true));
        }
        
        public async Task<IActionResult> GetProvince(Guid? provinceId,bool isEmpty = true)
        {
            return Json(SelectListItemHelper.GetListByT((await _provinceServices.GetAllAsync()).Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.ProvinceName, Selected = provinceId != null && provinceId == x.ID }), isEmpty));
        }
        public async Task<IActionResult> GetCity(Guid? provinceId, Guid? cityId, bool isEmpty = true)
        {
            return Json(SelectListItemHelper.GetListByT((await _cityServices.GetManyAsync(new DirectSpecification<Project_SYS_City>(x => x.ProvinceId == provinceId))).Select(x => new SelectListItem{ Value= x.ID.ToString(),Text= x.CityName, Selected = cityId != null && cityId == x.ID }), isEmpty));
        }
        public async Task<IActionResult> GetDistrict(Guid? cityId, Guid? districtId, bool isEmpty = true)
        {
            return Json(SelectListItemHelper.GetListByT((await _districtServices.GetManyAsync(new DirectSpecification<Project_SYS_District>(x => x.CityId == cityId))).Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.DistrictName, Selected = districtId != null && districtId == x.ID }), isEmpty));
        }
        #endregion
        // GET: Admin/System
        #region 模块管理
        public async Task<IActionResult> Module(Guid? PId = null)
        {
            ViewBag.PId = PId ?? Guid.Empty;
            var opt = new JqGridOpt();
            if (PId == null)
            {
                opt.OptMainFun = "ModuleOpt";
                opt.OptWidth = 100;
            }
            else
            {
                var pid = (await _moduleServices.GetByKeyAsync(PId))?.PID;
                opt.OptMainFun = "ModuleOpt";
                opt.OptWidth = 100;
                ViewBag.Back = "/Admin/System/Module" + (pid == Guid.Empty ? "" : "?PID=" + pid);
            }
            ViewBag.ColumsTitle = GetColumsName<ModuleDTO>(opt);
            ViewBag.DataUrl = "/Admin/System/GetModuleList";

            return View();
        }
        public IActionResult AddModule()
        {
            return View("ModuleDetail", new Project_SYS_Module());
        }

        public async Task<IActionResult> EditModule(Guid Id)
        {
            var model = (await _moduleServices.GetByKeyAsync(Id));
            model.ModuleActions =
                (await _moduleActionServices.GetManyAsync(
                    new DirectSpecification<Project_SYS_ModuleAction>(x => !x.IsDeleted && x.ModuleID == Id))).ToList();
            return View("ModuleDetail", model);
        }

        [HttpPost]
        
        [SubAuth(nameof(AddModule), nameof(EditModule))]
        public async Task<IActionResult> SaveModule(Project_SYS_Module model)
        {
            var oldid = model.ID;
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                x.Success = true;
                await _moduleServices.AddModule(model);
                x.Message = "" + (oldid == Guid.Empty ? "添加" : "编辑") + "成功!";
            });
            return Json(result);
        }

        [SubAuth(nameof(Module))]
        public async Task<IActionResult> GetModuleList(int page, int rows, string sidx, string sord,Guid pid)
        {
            var sort = !string.IsNullOrEmpty(sidx) ? new Dictionary<string, string>() { { sidx, sord.ToUpper() } } : new Dictionary<string, string>() { { "OrderID", "ASC" } };
            return Json(GetRowToGrid((await _moduleServices.GetModuleList(page, rows, pid, sort))));
        }

        public async Task<IActionResult> DelModule(string ids)
        {
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                if (ids.Split(',').Any())
                {
                    var delId = ids.Split(',').Select(Guid.Parse);
                    await _moduleServices.DelModule(delId);
                    x.Success = true;
                    x.Message = "删除成功!";
                }
            });
            return Json(result);
        }
        #endregion
        #region 角色管理
        public IActionResult Role()
        {
            ViewBag.ColumsTitle = GetColumsName<RoleDTO>();
            ViewBag.DataUrl = "/Admin/System/GetRoleList";
            return View();
        }
        public async Task<IActionResult> AddRole()
        {
            await LoadModuleList(Guid.Empty);
            return View("RoleDetail", new Project_SYS_Role());
        }

        public async Task<IActionResult> EditRole(Guid Id)
        {
            await LoadModuleList(Id);
            return View("RoleDetail", (await _roleServices.GetByKeyAsync(Id)));
        }

        async Task LoadModuleList(Guid Id)
        {
            ViewBag.ModuleList =await _moduleServices.LoadModuleList(Id);
        }
        [HttpPost]
        [SubAuth(nameof(AddRole), nameof(EditRole))]
        
        public async Task<IActionResult> SaveRole(Project_SYS_Role model, List<Project_SYS_ModuleAction> moduleAction)
        {
            var oldid = model.ID;
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                x.Success = true;
                await _roleServices.AddRole(model, moduleAction);
                x.Message = "" + (oldid == Guid.Empty ? "添加" : "编辑") + "成功!"+ (oldid == Guid.Empty ? "" : "若涉及当前账户角色修改,请重新登录一次才能变更!") + "";
            });
            return Json(result);
        }
        [SubAuth(nameof(Role))]
        public async Task<IActionResult> GetRoleList(int page, int rows, string sidx, string sord)
        {
            var sort = !string.IsNullOrEmpty(sidx) ? new Dictionary<string, string>() { { sidx, sord.ToUpper() } } : new Dictionary<string, string>() { { "OrderID", "ASC" } };
            return Json(GetRowToGrid(await _roleServices.GetRoleList(page, rows, sort)));
        }
        public async Task<IActionResult> DelRole(string ids)
        {
            TipResult result = new TipResult();
            await result.RunWithAsyncTry(async x =>
            {
                if (ids.Split(',').Any())
                {
                    var delId = ids.Split(',').Select(Guid.Parse);
                    await _roleServices.DelRole(delId);
                    x.Success = true;
                    x.Message = "删除成功!";
                }

Solution/Company.Project.Web.Admin/Areas/Admin/Controllers/ViewComponents/ModuleActionBtnViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Company.Project.Web.Admin.Areas.Admin.Lib;
using Microsoft.AspNetCore.Mvc;

namespace Company.Project.Web.Admin.Areas.Admin
{
    public class ModuleActionBtnViewComponent : ViewComponent
    {
        private readonly ILocalCommon _localCommon;
        public ModuleActionBtnViewComponent(ILocalCommon localCommon)
        {
            _localCommon = localCommon;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View("/Areas/Admin/Views/Shared/ViewComponents/ModuleActionBtn/Default.cshtml", await _localCommon.CurrentFullUserAsync());
        }
    }
}

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/AdminLog.cshtml
@{
    ViewBag.Title = "系统日志";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Js{
    <script src="~/Areas/Admin/js/System/AdminLog.js"></script>
}
<div class="row">
    <div class="col-xs-12">
        <form id="SearchForm">
            <div class="ui-filter clearfix">
                <!--在此处添加客户代码-->
                <div class="btn-group search-group">
                    <label class="control-label">记录时间</label>
                    <input style="width: 100px;" type="text" id="SearchStartCreateTime" name="SearchStartCreateTime" />-
                    <input style="width: 100px;" type="text" id="SearchEndCreateTime" name="SearchEndCreateTime" />
                </div>
                <div class="btn-group search-group">
                    <label class="control-label">&nbsp;</label>
                    <input style="width: 200px;" type="text" id="SearchText" name="SearchText" />
                    @*客户代码结束*@
                    <button id="btnSearch" class="btn btn-info btn-lg btn-white ui-btn-search" type="button">
                        <i class="ace-icon fa fa-search bigger-110"></i>
                        查询
                    </button>
                </div>

            </div>
            @await Component.InvokeAsync("ModuleActionBtn")
        </form>
        @Html.Partial("~/Areas/Admin/Views/Shared/_GeneralGrid.cshtml")
    </div>
</div>

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/Manager.cshtml
@using Company.Project.Infrastructure.Common.Enums
@using Company.Project.Domain.Model.DTO
@{
    ViewBag.Title = "系统用户管理";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Js{
    <script src="~/Areas/Admin/js/System/Manager.js"></script>
}
<div class="row">
    <div class="col-xs-12">
        <form id="SearchForm">
            <div class="ui-filter clearfix">
                <!--在此处添加客户代码-->
                <div class="btn-group search-group">
                    <label class="control-label">用户状态</label>
                    <select class="input-medium" id="SeachState" name="SeachState" ajax-url="/Admin/System/GetEnumManagerState?isEmpty=true" style="height: 38px;"></select>
                    <label class="control-label">角色</label>
                    <select class="input-medium" id="Role" name="Role" ajax-url="/Admin/System/GetRoeLsit?isEmpty=false" style="height: 38px;"></select>
                </div>
                <div class="btn-group search-group">
                    <label class="control-label">登录名</label>
                    <input type="text" style="height: 38px; padding: 0px; margin: 0px;" name="sealogin"/>
                    <button id="btnSearch" class="btn btn-info btn-lg btn-white ui-btn-search" type="button">
                        <i class="ace-icon fa fa-search bigger-110"></i>
                        查询
                    </button>
                </div>

            </div>
            @await Component.InvokeAsync("ModuleActionBtn")
        </form>
        @Html.Partial("~/Areas/Admin/Views/Shared/_GeneralGrid.cshtml")
    </div>
</div>

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/ManagerDetail.cshtml
@using Company.Project.Domain.Model
@model Project_Manager_BaseInfo
@Html.HiddenFor(x => x.ID)
@using Company.Project.Domain.Model.DTO.Manager
@{
    var RoleLsit = (List<RoleListDTO>)ViewBag.RoleList;
}

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>登录名</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="LoginName" name="LoginName" required maxlength="20" @(Model.ID!=Guid.Empty?"readonly=\"readonly\"":"") checkeng="true" value="@Model.LoginName" placeholder="请输入登录名" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">密码</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="password" id="PassWord" @Html.Raw(Model.ID!=Guid.Empty ? "" : " minlength=\"6\"  maxlength=\"12\"") name="PassWord" @(string.IsNullOrEmpty(Model.PassWord) ? "required" : "") value="@(string.IsNullOrEmpty(Model.PassWord)?Model.PassWord:"")" placeholder="请输入密码" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>昵称</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="NickName" name="NickName" required maxlength="20" value="@Model.NickName" placeholder="请输入昵称" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">状态</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="State" name="State" ajax-url="/Admin/System/GetEnumManagerState?code=@Model.State"></select>

        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">用户角色</label>
    @{
        foreach (RoleListDTO item in RoleLsit)
        {
            <div class="roel">
                <input type="checkbox" class='ace actionid' @Html.Raw(item.Ischeck ? "checked=\"checked\"" : "") value="@item.ID">
                <span class="lbl"><span style="margin-left: 6px;">@item.RoleName</span> </span>
            </div>
        }
    }

</div>
<script src="~/Areas/Admin/js/System/ManagerDetail.js"></script>
<style type="text/css">
    .roel {
        margin-top: 9px;
        float: left;
        margin-left: 8px;
    }
</style>

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/Module.cshtml
@{
    ViewBag.Title = "模块管理";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@section Js
{
<script src="~/Areas/Admin/js/System/Module.js"></script>
}
<div class="row">
    <div class="col-xs-12">
        <form id="SearchForm">
            <div class="ui-filter clearfix">
                <input type="hidden" name="PID" value="@ViewBag.PId" />
            </div>
            @await Component.InvokeAsync("ModuleActionBtn")
        </form>
        @Html.Partial("~/Areas/Admin/Views/Shared/_GeneralGrid.cshtml")
    </div>
</div>

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/ModuleDetail.cshtml
@using Company.Project.Domain.Model
@model Project_SYS_Module
@Html.HiddenFor(x=>x.ID)
@Html.HiddenFor(x => x.ModuleUrl)

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"> <span style="color: red">*</span>模块名称 </label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="ModuleName" name="ModuleName" required value="@Model.ModuleName" placeholder="请输入模块名称" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"> 父级模块 </label>
    <div class="col-sm-9">
        <div class="clearfix">
            <select class="input-medium" id="PID" name="PID" ajax-url="/Admin/System/GetFatherModule?fatherId=@Model.PID&itemId=@Model.ID"></select>
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span> 排序编号 </label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="OrderID" name="OrderID" required digits="true" value="@Model.OrderID" placeholder="请输入排序编号" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"> 模块样式 </label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="ModuleCls" name="ModuleCls" value="@Model.ModuleCls" placeholder="请输入模块样式" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"> 模块功能 </label>
    <div class="col-sm-9">
        <div class="fieldset">
            <a class="btn btn-xs" id="addChild"><i class="ace-icon fa fa-plus-circle"></i>新增</a>
            <a class="btn btn-xs" id="addChildDef"><i class="ace-icon fa fa-plus-circle"></i>新增默认(增、删、改、查、导)</a>
            <input class="input-small" style="margin-left: 20px;" id="defConroller" placeholder="默认控制器名"/><input id="defMainAction" style="margin-left: 20px;" class="input-small" placeholder="默认主方法名"/>
        </div>
    </div>
</div>
<div class="form-group actionList">

</div>
<script src="~/Areas/Admin/js/System/ModuleDetail.js"></script>
<script type="text/javascript">
    $(function () {
        setTimeout(function() {
        @{
            if (Model.ModuleActions != null)
            {
                foreach (var action in Model.ModuleActions.OrderBy(x => x.OrderID).Where(x => !x.IsDeleted))
                {
                    @:parent.addItem({ ID: "@action.ID", ActionName: "@action.ActionName", ActionUrl: "@action.ActionUrl", OrderID: "@action.OrderID", ShowEnum: "@action.ShowEnum.ToString()", ActionCls: "@action.ActionCls", ActionFun: "@action.ActionFun" });
                }
            }
        }
        }, 100);
    });
</script>

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/Role.cshtml
@{
    ViewBag.Title = "角色管理";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-xs-12">
        <form id="SearchForm">
            <div class="ui-filter clearfix">
            </div>
            @await Component.InvokeAsync("ModuleActionBtn")
        </form>
        @Html.Partial("~/Areas/Admin/Views/Shared/_GeneralGrid.cshtml")
    </div>
</div>

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/RoleDetail.cshtml
@using Company.Project.Domain.Model
@using Company.Project.Domain.Model.DTO.Manager
@{
    var ModuleList = (List<MenuModuleListDTO>)ViewBag.ModuleList;
}
@model Project_SYS_Role
@Html.HiddenFor(x => x.ID)

<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>角色名称</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="RoleName" name="RoleName" required maxlength="20" value="@Model.RoleName" placeholder="请输入角色名称" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right">角色描述</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="Memo" name="Memo" value="@Model.Memo" maxlength="50" placeholder="请输入角色描述" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
<div class="form-group">
    <label class="col-sm-3 control-label no-padding-right"><span style="color: red">*</span>排序编号</label>
    <div class="col-sm-9">
        <div class="clearfix">
            <input type="text" id="OrderID" name="OrderID" required maxlength="9" digits="true" value="@(Model.OrderID)" placeholder="请输入排序编号" class="col-xs-10 col-sm-5">
        </div>
    </div>
</div>
@{
    foreach (var MainModule in ModuleList)
    {
        <div class="form-group moduleList">
            <div class="col-sm-12 title">
                <h4>@MainModule.ModuleName</h4>
            </div>
            @foreach (var ChildModule in MainModule.ChildModule)
            {
                <div class="col-sm-11">
                    <h5 style="float: left; width: 150px; text-align: right">@ChildModule.ModuleName</h5>
                    @if (ChildModule.ChildAction.Any())
                    {
                        <div class="contents">
                            <ul>
                                @foreach (var action in ChildModule.ChildAction)
                                {
                                    <li>
                                        <label>
                                            @if (action.IsMenu)
                                            {
                                                <input type="checkbox" @Html.Raw(action.IsCheck ? "checked=\"checked\"" : "") value="@action.ID" class="ace actionid mainaction">
                                                <span class="lbl">
                                                    <strong>@action.ActionName</strong>
                                                </span>
                                            }
                                            else
                                            {
                                                <input type="checkbox" @Html.Raw(action.IsCheck ? "checked=\"checked\"" : "") value="@action.ID" class="ace actionid otheraction">
                                                <span class="lbl">
                                                    @action.ActionName
                                                </span>
                                            }
                                        </label>
                                    </li>
                                }
                            </ul>
                        </div>
                    }
                    else
                    {
                        if (ChildModule.ThreeChildModule != null && ChildModule.ThreeChildModule.Any())
                        {
                            foreach (var ThreeChildModule in ChildModule.ThreeChildModule)
                            {
                                <div class="col-sm-11">
                                    <h6 style="float: left; width: 180px; text-align: right">@ThreeChildModule.ModuleName</h6>
                                    @if (ThreeChildModule.ChildAction.Any())
                                    {
                                        <div class="contents">
                                            <ul>
                                                @foreach (var action in ThreeChildModule.ChildAction)
                                                {
                                                    <li>
                                                        <label>
                                                            @if (action.IsMenu)
                                                            {
                                                                <input type="checkbox" @Html.Raw(action.IsCheck ? "checked=\"checked\"" : "") value="@action.ID" class="ace actionid mainaction">
                                                                <span class="lbl">
                                                                    <strong>@action.ActionName</strong>
                                                                </span>
                                                            }
                                                            else
                                                            {
                                                                <input type="checkbox" @Html.Raw(action.IsCheck ? "checked=\"checked\"" : "") value="@action.ID" class="ace actionid otheraction">
                                                                <span class="lbl">
                                                                    @action.ActionName
                                                                </span>
                                                            }
                                                        </label>
                                                    </li>
                                                }
                                            </ul>
                                        </div>
                                    }
                                </div>
                            }
                        }
                    }
                </div>
            }
            <div class="col-sm-12 clear"></div>
        </div>
    }
}
<style type="text/css">
    .clear {
        clear: both;
        border-bottom: 1px dotted #e2e2e2;
    }

    .moduleList .title {
        border-bottom: 1px dotted #e2e2e2;
    }

    .moduleList .contents {
        margin-left: 10px;
        float: left;
    }

    .moduleList ul li {
        list-style-type: none;
        float: left;
        line-height: 36px;
        padding: 0px 10px;
    }
</style>
<script src="~/Areas/Admin/js/System/RoleDetail.js"></script>

Solution/Company.Project.Web.Admin/Areas/Admin/Views/System/WeChatSettingDetail.cshtml
@using Company.Project.Domain.Model
@{
    ViewBag.Title = "微信公众号设置";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@model Project_SYS_WeChatSetting

<div class="modal-content">
    <form class="form-horizontal" id="formDetail" role="form">
        <div class="modal-header">
            <h3 class="smaller lighter blue no-margin">微信基本设置</h3>
        </div>

        <div class="modal-body">
            @Html.HiddenFor(x => x.ID)
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right">公众号名称</label>
                <div class="col-sm-9">
                    <div class="clearfix">
                        <input type="text" id="WeChatName" name="WeChatName" required maxlength="60" value="@Model.WeChatName" placeholder="请输入公众号名称" class="col-xs-10 col-sm-5">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right">公众号原始ID</label>
                <div class="col-sm-9">
                    <div class="clearfix">
                        <input type="text" id="WxChat_gID" name="WxChat_gID" required maxlength="50" value="@Model.WxChat_gID" placeholder="请输入公众号原始ID" class="col-xs-10 col-sm-5">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right">微信Token</label>
                <div class="col-sm-9">
                    <div class="clearfix">
                        <input type="text" id="Token" name="Token" required maxlength="50" value="@Model.Token" placeholder="请输入微信Token" class="col-xs-10 col-sm-5">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right">微信绑定Url</label>
                <div class="col-sm-9">
                    <div class="clearfix">
                        <input type="text" id="BindUrl" name="BindUrl" required  maxlength="200" value="@Model.BindUrl" placeholder="请输入微信绑定Url" class="col-xs-10 col-sm-5">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right">AppID</label>
                <div class="col-sm-9">
                    <div class="clearfix">
                        <input type="text" id="AppID" name="AppID" required maxlength="50" value="@Model.AppID" placeholder="请输入AppID" class="col-xs-10 col-sm-5">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right">AppSecret</label>
                <div class="col-sm-9">
                    <div class="clearfix">
                        <input type="text" id="AppSecret" name="AppSecret" maxlength="50" required value="@Model.AppSecret" placeholder="请输入AppSecret" class="col-xs-10 col-sm-5">
                    </div>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <a class="btn btn-sm btn-success pull-right" id="saveBtn">
                <i class="ace-icon fa fa-check"></i>
                保存
            </a>
        </div>
    </form>
</div>
<script src="~/Areas/Admin/js/System/WeChatSettingDetail.js"></script>